_base_: [
    '../../../_base_/base.py',
    '../../../_base_/model.py',
    '../../../_base_/data.py',
    '../../../_base_/optimizer.py'
]

name: det-da-frcnn-finetune-train
type: DetectionTrainer

optimizer:
    lr: 0.002

evaluation:
    interval: 1
    metric: bbox
    classwise: true
