_base_: ../train.yaml

name: det-ta-ssd-incremental-train-lwf-off
type: Trainer

task_adapt:
    op: MERGE  # REPLACE | MERGE
    online_mode: false

hparams:
    dummy: 0

optimizer:
  lr: 0.002

evaluation:
    interval: 1
    metric: bbox
    classwise: true

