stages:
    - name: finetune
      type: DetectionTrainer
      task: detection
      mode: train
      config: {{ fileDirname }}/train.yaml
      output:
          - final_ckpt

    - name: final-eval
      type: DetectionEvaluator
      task: detection
      mode: train
      config: {{ fileDirname }}/eval.yaml
      input:
          pretrained:
              stage_name: finetune
              output_key: final_ckpt

    - name: eval-only
      type: DetectionEvaluator
      task: detection
      mode: eval
      config: {{ fileDirname }}/eval.yaml
      input:
          pretrained:
              stage_name: finetune
              output_key: final_ckpt

hparams:
    dummy: 0
