stages:
    - name: finetune1
      type: DetectionTrainer
      task: detection
      mode: train
      config: {{ fileDirname }}/train_baseline.yaml
      output:
          - final_ckpt


    - name: finetune2
      type: DetectionTrainer
      task: detection
      mode: train
      config: {{ fileDirname }}/train.yaml
      input:
          pretrained:
              stage_name: finetune1
              output_key: final_ckpt
      output:
          - final_ckpt

    - name: final-eval
      type: DetectionEvaluator
      task: detection
      mode: train
      config: {{ fileDirname }}/eval.yaml
      input:
          pretrained:
              stage_name: finetune2
              output_key: final_ckpt

    - name: eval-only
      type: DetectionEvaluator
      task: detection
      mode: eval
      config: {{ fileDirname }}/eval.yaml
      input:
          pretrained:
              stage_name: finetune2
              output_key: final_ckpt

hparams:
    dummy: 0
