_base_:
    - {{ fileDirname }}/../_base_/default_runtime.py

stages:
    - name: det
      task: detection
      mode: train
      type: DetectionTrainer
      config: {{ fileDirname }}/stage_otedet.yaml
    #- name: det_eval
    #  task: detection
    #  mode: eval
    #  type: DetectionEvaluator
    #  config: {{ fileDirname }}/stage_otedet.yaml
