stages:
    - name: finetune
      type: DetectionTrainer
      task: detection
      mode: train
      config: {{ fileDirname }}/train.py
      output:
          - final_ckpt

    - name: final-eval
      type: DetectionEvaluator
      task: detection
      mode: train
      config: {{ fileDirname }}/train.py
      input:
          pretrained:
              stage_name: finetune
              output_key: final_ckpt  # stage_name: output_key

    - name: eval-only
      type: DetectionEvaluator
      task: detection
      mode: eval
      config: {{ fileDirname }}/train.py

hparams:
    dummy: 0



