stages:
    - name: byol_train
      task: representation
      mode: train
      type: SelfSLTrainer
      img_size: !!python/tuple [112,112]
      downstream_config: {{ fileDirname }}/../classification/domain_adapt/finetune/train.yaml
      downstream_task: classification
      config: {{ fileDirname }}/byol.yaml
      output:
        - pretrained

    - name: cls_from_byol
      task: classification
      mode: train
      type: ClsTrainer
      config: {{ fileDirname }}/../classification/domain_adapt/finetune/train.yaml
      input:
        pretrained:
          stage_name: byol_train
          output_key: pretrained
      output:
        - final_ckpt
