version: '2.2'

services:
  ci-worker:
    privileged: true
    shm_size: '5g'
    cpuset: 0-23
    networks:
      - mpa_cpu
    container_name: mpa_cpu_image_${BUILD_NAME_SEED}
    image: registry.toolbox.iotg.sclab.intel.com/${MPA_IMAGE_NAME}:${MPA_IMAGE_TAG}
    volumes:
      - /validation/components-data/mpa/data:/usr/src/app/data
      - ./models:/usr/src/app/models
      - ./recipes:/usr/src/app/recipes
      - ./recipes_old:/usr/src/app/recipes_old
      - ./samples:/usr/src/app/samples
      - ./tests:/usr/src/app/tests
      - ./mpa:/usr/src/app/mpa
      - ./tools:/usr/src/app/tools
      - ./.reports:/usr/src/app/.reports
      - ${BUILD_LOGS}:/usr/src/app/logs
    command:
      - /bin/sleep
      - infinity

networks:
  mpa_cpu:
    driver: bridge
    name: mpa_cpu_${BUILD_NAME_SEED}
