stages:
  - name: hpo
    type: HpoRunner
    mode: train
    hpo:
      trainer:
          type: ClsTrainer
          config: {{ fileDirname }}/train.yaml
      hyperparams:
        - {name: 'lr', type: 'loguniform', range: [0.0001, 0.1]}
        - {name: 'bs', type: 'qloguniform', range: [2, 128, 2]}
      metric: 'accuracy_top-1'
      num_trials: 30
      max_iterations: 10
      subset_size: 5000
      search_alg: 'asha' # 'bayes_opt'
      gpu_list: [0]
    output:
      - hyperparams

  - name: finetune
    type: ClsTrainer
    mode: train
    config: {{ fileDirname }}/train.yaml
    input:
      hyperparams:
        stage_name: hpo
        output_key: hyperparams
    output:
      - final_ckpt

  - name: evaluation
    type: ClsEvaluator
    mode: train
    config: {{ fileDirname }}/eval.yaml
    input:
      pretrained:
        stage_name: finetune
        output_key: final_ckpt

  - name: exporter
    type: ClsExporter
    mode: export
    config: {{ fileDirname }}/eval.yaml
