_base_: [
    '../../_base_/base.py',
    '../../_base_/model.py',
    '../../_base_/data.py',
    '../../_base_/optimizer.py'
]

model:
    pretrained: mmcls://mobilenet_v2
    backbone:
        type: MobileNetV2
        widen_factor: 1.0

optimizer:
    type: SGD
    lr: 0.003
    momentum: 0.9

runner:
    max_epochs: 10

checkpoint_config:
    interval: 2

evaluation:
    metric: accuracy
