_base_ :
    - '../../_base_/data.py'
    - '../../_base_/base.py'
    - '../../_base_/optimizer.py'

data:
    samples_per_gpu: 2

runner:
    type: IterBasedRunner
    max_iters: 80000

checkpoint_config:
    interval: 8000

evaluation:
    interval: 8000
