stages:
    - name: task-adapt
      type: DetectionTrainer
      task: detection
      mode: train
      config: {{ fileDirname }}/train.yaml
      output:
          - final_ckpt

    - name: final-eval
      type: DetectionEvaluator
      task: detection
      mode: train
      config: {{ fileDirname }}/../eval.yaml
      input:
          pretrained:
              stage_name: task-adapt
              output_key: final_ckpt  # stage_name: output_key

    - name: eval-only
      type: DetectionEvaluator
      task: detection
      mode: eval
      config: {{ fileDirname }}/../eval.yaml

hparams:
    dummy: 0

