_base_: ../train.yaml

name: det-ta-ssd-custom-train
type: DetectionTrainer

task_adapt:
    op: REPLACE  # REPLACE | MERGE

hparams:
    dummy: 0

optimizer:
  lr: 0.002

evaluation:
    interval: 1
    metric: bbox
    classwise: true

