stages:
  - name: ssl-fixmatch
    type: ClsTrainer
    mode: train
    config: {{ fileDirname }}/train.yaml
    output:
      - final_ckpt

  - name: evaluation
    type: ClsEvaluator
    mode: train
    config: {{ fileDirname }}/eval.yaml
    input:
      pretrained:
        stage_name: ssl-fixmatch
        output_key: final_ckpt