_base_: [
    '../../_base_/base.py',
    '../../_base_/model.py',
    '../../_base_/data.py',
    '../../_base_/optimizer.py'
]

model:
    type: SemiSLClassifier
    pretrained: mmcls://mobilenet_v2
    backbone:
        type: MobileNetV2
        widen_factor: 1.0
    head:
        type: SemiSLClsHead
        in_channels: 1280

# custom_hooks:
#   - type: GPUMonitorHook

runner:
    type: 'EpochBasedRunner'
    max_epochs: 200

optimizer:
    type: SGD
    lr: 0.001
    momentum: 0.9

evaluation:
    metric: accuracy