_base_: ../../../../../models/detection/ote_ssd_person-detection-0201.py

name: det-da-ssd-finetune-train
type: DetectionTrainer

hparams:
    dummy: 0

data:
    samples_per_gpu: 2  # 84 in OTE setting
    workers_per_gpu: 2  # 3 in OTE setting

log_config:
    interval: 100

optimizer:
    lr: 0.0002

evaluation:
    interval: 1
    metric: bbox
    classwise: true

