stages:
  - name: pre-stage
    type: ClsInferrer
    task: classification
    mode: train
    config: {{ fileDirname }}/train.yaml
    output:
      - pre_stage_res
  - name: cls-inc
    type: ClsTrainer
    task: classification
    mode: train
    config: {{ fileDirname }}/train.yaml
    input:
      pre_stage_res:
        stage_name: pre-stage
        output_key: pre_stage_res  # stage_name: output_key
    output:
      - final_ckpt

  - name: cls-inc-evaluation
    type: ClsEvaluator
    task: classification
    mode: train
    config: {{ fileDirname }}/eval.yaml
    input:
      pretrained:
        stage_name: cls-inc
        output_key: final_ckpt
  - name: cls-inc-evaluation
    type: ClsEvaluator
    task: classification
    mode: eval
    config: {{ fileDirname }}/eval.yaml
