_base_: [
    '../../../_base_/base.py',
    '../../../_base_/model.py',
    '../../../_base_/data.py',
    '../../../_base_/optimizer.py'
]

name: cls-inc
optimizer:
    type: Adam
    lr: 0.0003
    weight_decay: 0.001
optimizer_config:
  grad_clip:
lr_config:
  policy: 'CosineAnnealing'
  min_lr_ratio: 0.0
runner:
  type: 'EpochBasedRunner'
  max_epochs: 20
log_config:
  interval: 10
workflow:
  - !!python/tuple
    - train
    - 1
checkpoint_config:
    type: CheckpointHookWithValResults
    interval: 1
evaluation:
    metric: ['accuracy', 'class_accuracy']
task_adapt:
    type: sampling_old
    num_old_data_samples: 0.2 # apply ratio when num_old_data_samples < 1
    op: MERGE  # REPLACE | MERGE
    online_mode: false

