_base_: ../../../../models/detection/ote_ssd_person-detection-0202.py
#_base_: ../../../../external/mmdetection/configs/ssd/ssd512_coco.py
#_base_: ../../../../external/mmdetection/configs/ssd/ssd300_coco.py

name: det-ta-ssd-train
type: DetectionTrainer

task_adapt:
    op: REPLACE  # REPLACE | MERGE

hparams:
    dummy: 0

data:
    samples_per_gpu: 8  # 84 in OTE setting
    workers_per_gpu: 2  # 3 in OTE setting
    train:
    #    times: 1
        dataset:
            min_size: 0

log_config:
    interval: 100

optimizer:
  lr: 0.002

evaluation:
    interval: 1
    metric: bbox
    classwise: true

